import { Project } from '../types';

export const agriculturalProjects: Project[] = [
  {
    id: 401,
    title: 'مشروع زراعة الخضروات',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الخضروات.png',
  },
  {
    id: 402,
    title: 'مشروع زراعة الفواكه',
    description: '',
    capital: 250000,
    monthlyProfit: 50000,
    studyCost: 200,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الفواكه.png',
  },
  {
    id: 403,
    title: 'مشروع زراعة العنب',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 180,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-العنب.png',
  },
  {
    id: 404,
    title: 'مشروع زراعة الزيتون',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 200,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الزيتون.png',
  },
  {
    id: 405,
    title: 'مشروع زراعة التمور',
    description: '',
    capital: 300000,
    monthlyProfit: 60000,
    studyCost: 250,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-التمور.png',
  },
  {
    id: 406,
    title: 'مشروع زراعة الحمضيات',
    description: '',
    capital: 280000,
    monthlyProfit: 56000,
    studyCost: 220,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الحمضيات.png',
  },
  {
    id: 407,
    title: 'مشروع زراعة المحاصيل',
    description: '',
    capital: 350000,
    monthlyProfit: 70000,
    studyCost: 250,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-المحاصيل.png',
  },
  {
    id: 408,
    title: 'مشروع زراعة الحبوب',
    description: '',
    capital: 400000,
    monthlyProfit: 80000,
    studyCost: 300,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الحبوب.png',
  },
  {
    id: 409,
    title: 'مشروع زراعة البقوليات',
    description: '',
    capital: 160000,
    monthlyProfit: 32000,
    studyCost: 180,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-البقوليات.png',
  },
  {
    id: 410,
    title: 'مشروع إنتاج الشتلات',
    description: '',
    capital: 120000,
    monthlyProfit: 24000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/انتاج-الشتلات.png',
  },
  {
    id: 411,
    title: 'مشروع إنتاج البذور',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 200,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/انتاج-البذور.png',
  },
  {
    id: 412,
    title: 'مشروع زراعة الأعشاب الطبية',
    description: '',
    capital: 140000,
    monthlyProfit: 28000,
    studyCost: 170,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الاعشاب-الطبية.png',
  },
  {
    id: 413,
    title: 'مشروع زراعة الورود',
    description: '',
    capital: 160000,
    monthlyProfit: 32000,
    studyCost: 180,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الورود.png',
  },
  {
    id: 414,
    title: 'مشروع زراعة النباتات الداخلية',
    description: '',
    capital: 130000,
    monthlyProfit: 26000,
    studyCost: 160,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-النباتات-الداخلية.png',
  },
  {
    id: 415,
    title: 'مشروع زراعة الأشجار المظللة',
    description: '',
    capital: 220000,
    monthlyProfit: 44000,
    studyCost: 200,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الاشجار-المظللة.png',
  }
];