import { Project } from '../types';

export const agriculturalProjects: Project[] = [
  {
    id: 1,
    title: 'مشروع زراعة البرتقال',
    description: '',
    capital: 50000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/البرتقال.png',
  },
  {
    id: 2,
    title: 'مشروع زراعة البطاطس',
    description: '',
    capital: 40000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-البطاطس.png',
  },
  {
    id: 3,
    title: 'مشروع زراعة الموز',
    description: '',
    capital: 45000,
    monthlyProfit: 9000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الموز.png',
  },
  {
    id: 24,
    title: 'مشروع زراعة البصل والثوم',
    description: '',
    capital: 30000,
    monthlyProfit: 6000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/البصل-والثوم.png',
  },
  {
    id: 25,
    title: 'مشروع زراعة التين البرشومي',
    description: '',
    capital: 35000,
    monthlyProfit: 7000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/التين-البرشومي.png',
  },
  {
    id: 26,
    title: 'مشروع زراعة الجزر',
    description: '',
    capital: 25000,
    monthlyProfit: 5000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/الجزر.png',
  },
  {
    id: 27,
    title: 'مشروع الزراعة المنزلية',
    description: '',
    capital: 15000,
    monthlyProfit: 3000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/الزراعة المنزلية.jpg',
  },
  {
    id: 28,
    title: 'مشروع زراعة السبانخ والخس',
    description: '',
    capital: 20000,
    monthlyProfit: 4000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/السبانخ-والخس.png',
  },
  {
    id: 29,
    title: 'مشروع زراعة القمح',
    description: '',
    capital: 45000,
    monthlyProfit: 9000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/القمح.png',
  },
  {
    id: 30,
    title: 'مشروع زراعة الكمثرى',
    description: '',
    capital: 40000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/الكمثري.png',
  },
  {
    id: 31,
    title: 'مشروع زراعة النعناع',
    description: '',
    capital: 15000,
    monthlyProfit: 3000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/النعناع.png',
  },
  {
    id: 32,
    title: 'مشروع زراعة الأرز البسمتي',
    description: '',
    capital: 50000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الأرز-البسمتي.png',
  },
  // ... المشروعات السابقة
  {
    id: 33,
    title: 'مشروع زراعة الكنتالوب',
    description: '',
    capital: 35000,
    monthlyProfit: 7000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الكنتالوب.png',
  },
  {
    id: 34,
    title: 'مشروع زراعة الكيوي',
    description: '',
    capital: 45000,
    monthlyProfit: 9000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-الكيوي.png',
  },
  {
    id: 35,
    title: 'مشروع زراعة المانجا',
    description: '',
    capital: 50000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-المانجا.png',
  },
  {
    id: 36,
    title: 'مشروع زراعة المشروم',
    description: '',
    capital: 30000,
    monthlyProfit: 6000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-المشروم.png',
  },
  {
    id: 37,
    title: 'مشروع زراعة المشمش',
    description: '',
    capital: 40000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-المشمش.png',
  },
  {
    id: 38,
    title: 'مشروع زراعة النخيل',
    description: '',
    capital: 60000,
    monthlyProfit: 12000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-النخيل.png',
  },
  {
    id: 39,
    title: 'مشروع زراعة دوار الشمس',
    description: '',
    capital: 25000,
    monthlyProfit: 5000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-دوار-الشمس.png',
  },
  {
    id: 40,
    title: 'مشروع زراعة صبار الألوفيرا',
    description: '',
    capital: 20000,
    monthlyProfit: 4000,
    studyCost: 150,
    category: 'agriculture',
    imageUrl: '/images/مشروعات الزراعيه/زراعة-صبار-الألوفيرا.png',
  }
];