import { Project } from '../types';

export const industrialProjects: Project[] = [
  {
    id: 101,
    title: 'تصنيع البلاستيكات والمعادن',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-البلاستيكات-والمعادن.png',
  },
  {
    id: 102,
    title: 'تصنيع الصابون',
    description: '',
    capital: 120000,
    monthlyProfit: 24000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-الصابون.png',
  },
  {
    id: 103,
    title: 'تصنيع العطور ومستحضرات التجميل',
    description: '',
    capital: 280000,
    monthlyProfit: 56000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-العطور-ومستحضرات-التجميل.png',
  },
  {
    id: 104,
    title: 'تصنيع المجوهرات',
    description: '',
    capital: 800000,
    monthlyProfit: 160000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-المجوهرات.png',
  },
  {
    id: 105,
    title: 'تعبئة وتغليف',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تعبئة-وتغليف.png',
  },
  {
    id: 106,
    title: 'تصنيع النوافذ والأبواب',
    description: '',
    capital: 400000,
    monthlyProfit: 80000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تنصيع-النوافذ-والأبواب.png',
  },
  {
    id: 107,
    title: 'صناعة المخلل والمربى',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/صناعة-المخلل-والمربي.png',
  },
  {
    id: 108,
    title: 'منتجات صديقة للبيئة',
    description: '',
    capital: 300000,
    monthlyProfit: 60000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/منتجات-صديقة-للبيئه.png',
  },
  {
    id: 109,
    title: 'الأدوات الكهربائية البسيطة',
    description: '',
    capital: 600000,
    monthlyProfit: 120000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/الأدوات-الكهربائية-البسيطة.png',
  },
  {
    id: 110,
    title: 'الأكياس الورقية',
    description: '',
    capital: 100000,
    monthlyProfit: 20000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/الأكياس-الورقية.png',
  },
];