import { Project } from '../types';

export const industrialProjects: Project[] = [
  {
    id: 101,
    title: 'تصنيع البلاستيكات والمعادن',
    description: '',
    capital: 50000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-البلاستيكات-والمعادن.png',
  },
  {
    id: 102,
    title: 'تصنيع الصابون',
    description: '',
    capital: 30000,
    monthlyProfit: 6000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-الصابون.png',
  },
  {
    id: 103,
    title: 'تصنيع العطور ومستحضرات التجميل',
    description: '',
    capital: 40000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-العطور-ومستحضرات-التجميل.png',
  },
  {
    id: 104,
    title: 'تصنيع المجوهرات',
    description: '',
    capital: 80000,
    monthlyProfit: 15000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-المجوهرات.png',
  },
  {
    id: 105,
    title: 'تعبئة وتغليف',
    description: '',
    capital: 35000,
    monthlyProfit: 7000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تعبئة-وتغليف.png',
  },
  {
    id: 106,
    title: 'تصنيع النوافذ والأبواب',
    description: '',
    capital: 60000,
    monthlyProfit: 12000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تنصيع-النوافذ-والأبواب.png',
  },
  {
    id: 107,
    title: 'صناعة المخلل والمربى',
    description: '',
    capital: 25000,
    monthlyProfit: 5000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/صناعة-المخلل-والمربي.png',
  },
  {
    id: 108,
    title: 'منتجات صديقة للبيئة',
    description: '',
    capital: 45000,
    monthlyProfit: 9000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/منتجات-صديقة-للبيئه.png',
  },
  {
    id: 109,
    title: 'الأدوات الكهربائية البسيطة',
    description: '',
    capital: 55000,
    monthlyProfit: 11000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/الأدوات-الكهربائية-البسيطة.png',
  },
  {
    id: 110,
    title: 'الأكياس الورقية',
    description: '',
    capital: 30000,
    monthlyProfit: 6000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/الأكياس-الورقية.png',
  },
  {
    id: 111,
    title: 'الألعاب الخشبية',
    description: '',
    capital: 35000,
    monthlyProfit: 7000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/الألعاب-الخشبية.png',
  },
  {
    id: 112,
    title: 'إنتاج الشموع والزيوت',
    description: '',
    capital: 40000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/أنتاج-الشموع-والزيوت.png',
  },
  {
    id: 113,
    title: 'إنتاج الشوكولاتة والحلويات',
    description: '',
    capital: 45000,
    monthlyProfit: 9000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/أنتاج-الشوكولاتات-والحلويات.png',
  },
  {
    id: 114,
    title: 'إنتاج الطوب والبلاط',
    description: '',
    capital: 70000,
    monthlyProfit: 14000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/أنتاج-الطوب-والبلاط.png',
  },
  {
    id: 115,
    title: 'إنتاج الكمامات والقفازات',
    description: '',
    capital: 50000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/أنتاج-الكمامات-والقفازات.png',
  },
  {
    id: 116,
    title: 'إنتاج المعكرونة',
    description: '',
    capital: 55000,
    monthlyProfit: 11000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/أنتاج-المعكرونة.png',
  },
  {
    id: 117,
    title: 'إنتاج الملابس الجاهزة',
    description: '',
    capital: 60000,
    monthlyProfit: 12000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/أنتاج-الملابس-الجاهزة.png',
  },
  {
    id: 118,
    title: 'إنتاج الورق والكرتون',
    description: '',
    capital: 65000,
    monthlyProfit: 13000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/أنتاج-الورق-والكرتون.png',
  },
  {
    id: 119,
    title: 'تدوير البلاستيك',
    description: '',
    capital: 75000,
    monthlyProfit: 15000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تدوير-البلاستيك.png',
  },
  {
    id: 120,
    title: 'تصنيع الأثاث',
    description: '',
    capital: 80000,
    monthlyProfit: 16000,
    studyCost: 150,
    category: 'industrial',
    imageUrl: '/images/مشروعات صناعيه/تصنيع-الأثاث.png',
  },
];