import { Project } from '../types';

export const livestockProjects: Project[] = [
  {
    id: 301,
    title: 'مشروع إنتاج الماشية',
    description: '',
    capital: 150000,
    monthlyProfit: 25000,
    studyCost: 250,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الماشية.png',
  },
  {
    id: 302,
    title: 'مشروع إنتاج الأغنام',
    description: '',
    capital: 80000,
    monthlyProfit: 15000,
    studyCost: 200,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الأغنام.png',
  },
  {
    id: 303,
    title: 'مشروع إنتاج الماعز',
    description: '',
    capital: 60000,
    monthlyProfit: 12000,
    studyCost: 200,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الماعز.png',
  },
  {
    id: 304,
    title: 'مشروع إنتاج الإبل',
    description: '',
    capital: 200000,
    monthlyProfit: 35000,
    studyCost: 300,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الإبل.png',
  },
  {
    id: 305,
    title: 'مشروع إنتاج الدواجن',
    description: '',
    capital: 120000,
    monthlyProfit: 22000,
    studyCost: 200,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الدواجن.png',
  },
  {
    id: 306,
    title: 'مشروع إنتاج الأرانب',
    description: '',
    capital: 40000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الأرانب.png',
  },
  {
    id: 307,
    title: 'مشروع إنتاج الأسماك',
    description: '',
    capital: 180000,
    monthlyProfit: 32000,
    studyCost: 250,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الأسماك.png',
  },
  {
    id: 308,
    title: 'مشروع إنتاج النحل',
    description: '',
    capital: 70000,
    monthlyProfit: 14000,
    studyCost: 180,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-النحل.png',
  },
  {
    id: 309,
    title: 'مشروع إنتاج الخيول',
    description: '',
    capital: 300000,
    monthlyProfit: 45000,
    studyCost: 300,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الخيول.png',
  },
  {
    id: 310,
    title: 'مشروع إنتاج الجمال',
    description: '',
    capital: 250000,
    monthlyProfit: 40000,
    studyCost: 280,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الجمال.png',
  },
  {
    id: 311,
    title: 'مشروع إنتاج الغزلان',
    description: '',
    capital: 280000,
    monthlyProfit: 42000,
    studyCost: 300,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الغزلان.png',
  },
  {
    id: 312,
    title: 'مشروع إنتاج الرومي',
    description: '',
    capital: 90000,
    monthlyProfit: 18000,
    studyCost: 180,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الرومي.png',
  },
  {
    id: 313,
    title: 'مشروع إنتاج البط',
    description: '',
    capital: 75000,
    monthlyProfit: 15000,
    studyCost: 170,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-البط.png',
  },
  {
    id: 314,
    title: 'مشروع إنتاج الوز',
    description: '',
    capital: 80000,
    monthlyProfit: 16000,
    studyCost: 170,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الوز.png',
  },
  {
    id: 315,
    title: 'مشروع إنتاج الحمام',
    description: '',
    capital: 45000,
    monthlyProfit: 9000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الحمام.png',
  },
  {
    id: 316,
    title: 'مشروع إنتاج الدجاج البلدي',
    description: '',
    capital: 85000,
    monthlyProfit: 17000,
    studyCost: 180,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الدجاج-البلدي.png',
  },
  {
    id: 317,
    title: 'مشروع إنتاج القواقع',
    description: '',
    capital: 50000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-القواقع.png',
  },
  {
    id: 318,
    title: 'مشروع إنتاج الجمبري',
    description: '',
    capital: 160000,
    monthlyProfit: 28000,
    studyCost: 220,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الجمبري.png',
  },
  {
    id: 319,
    title: 'مشروع إنتاج الأسماك البحرية',
    description: '',
    capital: 220000,
    monthlyProfit: 36000,
    studyCost: 250,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الأسماك-البحرية.png',
  },
  {
    id: 320,
    title: 'مشروع إنتاج أسماك الزينة',
    description: '',
    capital: 95000,
    monthlyProfit: 19000,
    studyCost: 180,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-أسماك-الزينة.png',
  }
];