import { Project } from '../types';

export const livestockProjects: Project[] = [
  {
    id: 10,
    title: 'مشروع تربية الأرانب',
    description: '',
    capital: 15000,
    monthlyProfit: 4000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الأرانب.png',
  },
  {
    id: 11,
    title: 'مشروع تربية النحل',
    description: '',
    capital: 20000,
    monthlyProfit: 5000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-النحل.png',
  },
  {
    id: 12,
    title: 'مشروع تربية الدواجن',
    description: '',
    capital: 35000,
    monthlyProfit: 7000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/مشروع الدواجن.jpg',
  },
  {
    id: 13,
    title: 'مشروع تربية السمان',
    description: '',
    capital: 25000,
    monthlyProfit: 5000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-السمان.png',
  },
  {
    id: 14,
    title: 'مشروع تربية الفئران',
    description: '',
    capital: 10000,
    monthlyProfit: 3000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الفئران.png',
  },
  {
    id: 15,
    title: 'مشروع تربية النعام',
    description: '',
    capital: 50000,
    monthlyProfit: 12000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-النعام.png',
  },
  {
    id: 16,
    title: 'مشروع تربية الغزلان',
    description: '',
    capital: 45000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-غزلان.png',
  },
  {
    id: 17,
    title: 'مشروع تربية الأبقار الحلاب',
    description: '',
    capital: 100000,
    monthlyProfit: 20000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/دراسة-جدوي-بقر-حلاب.png',
  },
  {
    id: 18,
    title: 'مشروع مزرعة دواجن لإنتاج البيض',
    description: '',
    capital: 80000,
    monthlyProfit: 15000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/مزرعة-الدواجن-لأنتاج-البيض.png',
  },
  {
    id: 19,
    title: 'مشروع تسمين العجول',
    description: '',
    capital: 120000,
    monthlyProfit: 25000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/مشروع-تسمين-عجول-.png',
  },
  {
    id: 20,
    title: 'مشروع الاستزراع السمكي في البحر',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/أسترزاع-سمكي-في-البحر.png',
  },
  {
    id: 21,
    title: 'مشروع دجاج اللحم',
    description: '',
    capital: 70000,
    monthlyProfit: 14000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/الدجاج لنتائج اللحوم.png',
  },
  {
    id: 22,
    title: 'مشروع المزارع السمكية',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/المزارع-السمكية.png',
  },
  {
    id: 23,
    title: 'مشروع إنتاج الألبان',
    description: '',
    capital: 90000,
    monthlyProfit: 18000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/أنتاج-الألبان.png',
  },
  {
    id: 24,
    title: 'مشروع تربية الإبل',
    description: '',
    capital: 180000,
    monthlyProfit: 35000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الأبل.png',
  },
  {
    id: 25,
    title: 'مشروع تربية الأوز',
    description: '',
    capital: 25000,
    monthlyProfit: 5000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الأوز.png',
  },
  {
    id: 26,
    title: 'مشروع تربية البط',
    description: '',
    capital: 20000,
    monthlyProfit: 4000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-البط.png',
  },
  {
    id: 27,
    title: 'مشروع تربية الحمام',
    description: '',
    capital: 15000,
    monthlyProfit: 3000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الحمام.png',
  },
  {
    id: 28,
    title: 'مشروع تربية الخيول',
    description: '',
    capital: 250000,
    monthlyProfit: 50000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الخيول.png',
  },
  {
    id: 29,
    title: 'مشروع تربية الديك الرومي',
    description: '',
    capital: 30000,
    monthlyProfit: 6000,
    studyCost: 150,
    category: 'livestock',
    imageUrl: '/images/مشروعات الثروه الحيوانية/تربية-الديك-الرومي.png',
  }
];