import { Project } from '../types';

export const serviceProjects: Project[] = [
  {
    id: 101,
    title: 'استشارات المشروعات الصغيرة',
    description: '',
    capital: 15000,
    monthlyProfit: 5000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/أستشارات-المشروعات-الصغيرة.png',
  },
  {
    id: 102,
    title: 'خدمات التسويق والإعلانات',
    description: '',
    capital: 20000,
    monthlyProfit: 7000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/التسويق-والأعلانات.png',
  },
  {
    id: 103,
    title: 'استوديو تصوير وفيديو',
    description: '',
    capital: 35000,
    monthlyProfit: 9000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/التصوير-والفيديو.png',
  },
  {
    id: 104,
    title: 'تنظيم الفعاليات والحفلات',
    description: '',
    capital: 40000,
    monthlyProfit: 12000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/الفعاليات-والحفلات.png',
  },
  {
    id: 105,
    title: 'خدمات تنظيف الشركات',
    description: '',
    capital: 25000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/تنظيف-الشركات.png',
  },
  {
    id: 106,
    title: 'خدمة توصيل الطلبات',
    description: '',
    capital: 30000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/توصيل-الطلبات-للمنازل.png',
  },
  {
    id: 107,
    title: 'خدمات الحاسوب والصيانة',
    description: '',
    capital: 20000,
    monthlyProfit: 6000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-الحاسوب.png',
  },
  {
    id: 108,
    title: 'مركز طباعة وتصميم',
    description: '',
    capital: 45000,
    monthlyProfit: 15000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-الطباعة-والتصميم.png',
  },
  {
    id: 109,
    title: 'مكتب محاسبة',
    description: '',
    capital: 25000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-المحاسبة.png',
  },
  {
    id: 110,
    title: 'خدمات النقل والشحن',
    description: '',
    capital: 60000,
    monthlyProfit: 20000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-النقل-والشحن.png',
  },
  {
    id: 111,
    title: 'وكالة سفر وسياحة',
    description: '',
    capital: 50000,
    monthlyProfit: 15000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-وسفر-وسياحة.png',
  },
  {
    id: 112,
    title: 'تأجير الأدوات والمعدات',
    description: '',
    capital: 40000,
    monthlyProfit: 12000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمة-تأجير-الأدوات-والمعدات.png',
  },
  {
    id: 113,
    title: 'صالون تجميل',
    description: '',
    capital: 35000,
    monthlyProfit: 10000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/صالون-تجميل.png',
  },
  {
    id: 114,
    title: 'مركز صيانة الأجهزة',
    description: '',
    capital: 30000,
    monthlyProfit: 9000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/صيانة-الأجهزة-الألكترونية.png',
  },
  {
    id: 115,
    title: 'مركز العناية بالحيوانات',
    description: '',
    capital: 45000,
    monthlyProfit: 13000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/مركز-العناية-بالحيوانات.png',
  },
  {
    id: 116,
    title: 'مركز تدريب مهارات',
    description: '',
    capital: 40000,
    monthlyProfit: 12000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/مركز-تدريب-المهارات.png',
  },
  {
    id: 117,
    title: 'مركز ترجمة',
    description: '',
    capital: 25000,
    monthlyProfit: 8000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/مركز-ترجمة.png',
  },
  {
    id: 118,
    title: 'مركز رعاية الأطفال',
    description: '',
    capital: 50000,
    monthlyProfit: 15000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/مركز-رعاية-الأطفال.png',
  },
  {
    id: 119,
    title: 'إدارة الممتلكات والعقارات',
    description: '',
    capital: 55000,
    monthlyProfit: 18000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/إدارة-الممتلكات-والعقارات.png',
  },
];