import { Project } from '../types';

export const serviceProjects: Project[] = [
  {
    id: 101,
    title: 'استشارات المشروعات الصغيرة',
    description: '',
    capital: 120000,
    monthlyProfit: 24000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/أستشارات-المشروعات-الصغيرة.png',
  },
  {
    id: 102,
    title: 'خدمات التسويق والإعلانات',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/التسويق-والأعلانات.png',
  },
  {
    id: 103,
    title: 'استوديو تصوير وفيديو',
    description: '',
    capital: 350000,
    monthlyProfit: 70000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/التصوير-والفيديو.png',
  },
  {
    id: 104,
    title: 'تنظيم الفعاليات والحفلات',
    description: '',
    capital: 450000,
    monthlyProfit: 90000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/الفعاليات-والحفلات.png',
  },
  {
    id: 105,
    title: 'خدمات تنظيف الشركات',
    description: '',
    capital: 280000,
    monthlyProfit: 56000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/تنظيف-الشركات.png',
  },
  {
    id: 106,
    title: 'خدمة توصيل الطلبات',
    description: '',
    capital: 320000,
    monthlyProfit: 64000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/توصيل-الطلبات-للمنازل.png',
  },
  {
    id: 107,
    title: 'خدمات الحاسوب والصيانة',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-الحاسوب.png',
  },
  {
    id: 108,
    title: 'مركز طباعة وتصميم',
    description: '',
    capital: 550000,
    monthlyProfit: 110000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-الطباعة-والتصميم.png',
  },
  {
    id: 109,
    title: 'مكتب محاسبة',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-المحاسبة.png',
  },
  {
    id: 110,
    title: 'خدمات النقل والشحن',
    description: '',
    capital: 650000,
    monthlyProfit: 130000,
    studyCost: 150,
    category: 'service',
    imageUrl: '/images/المشاريع الخدمية/خدمات-النقل-والشحن.png',
  },
  {
    id: 111,
    title: 'محل بيع شنط',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 112,
    title: 'محل بيع كماليات',
    description: '',
    capital: 120000,
    monthlyProfit: 24000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 113,
    title: 'محل بيع مستحضرات تجميل',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 114,
    title: 'محل بيع مستلزمات الأطفال',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 115,
    title: 'محل بيع مستلزمات الخياطة',
    description: '',
    capital: 130000,
    monthlyProfit: 26000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 116,
    title: 'محل بيع مستلزمات السفر',
    description: '',
    capital: 160000,
    monthlyProfit: 32000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 117,
    title: 'محل بيع مستلزمات المطبخ',
    description: '',
    capital: 170000,
    monthlyProfit: 34000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 118,
    title: 'محل بيع مستلزمات رجالية',
    description: '',
    capital: 140000,
    monthlyProfit: 28000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 119,
    title: 'محل بيع مستلزمات كهربائية',
    description: '',
    capital: 250000,
    monthlyProfit: 50000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 120,
    title: 'محل بيع مكيفات',
    description: '',
    capital: 300000,
    monthlyProfit: 60000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 121,
    title: 'محل بيع ملابس',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 122,
    title: 'محل بيع ملابس أطفال',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 123,
    title: 'محل بيع ملابس داخلية',
    description: '',
    capital: 120000,
    monthlyProfit: 24000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 124,
    title: 'محل بيع ملابس رجالية',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 125,
    title: 'محل بيع ملابس رياضية',
    description: '',
    capital: 220000,
    monthlyProfit: 44000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 126,
    title: 'محل بيع ملابس نسائية',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 127,
    title: 'محل بيع موبايلات',
    description: '',
    capital: 400000,
    monthlyProfit: 80000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 128,
    title: 'محل بيع وصلات كهربائية',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 129,
    title: 'محل بيع وصلات موبايل',
    description: '',
    capital: 120000,
    monthlyProfit: 24000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 130,
    title: 'محل بيع وشاحات',
    description: '',
    capital: 100000,
    monthlyProfit: 20000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 131,
    title: 'محل بيع ولاعات',
    description: '',
    capital: 100000,
    monthlyProfit: 20000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 132,
    title: 'محل تحميض صور',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 133,
    title: 'محل تصوير',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 134,
    title: 'محل تعبئة بطاقات شحن',
    description: '',
    capital: 100000,
    monthlyProfit: 20000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 135,
    title: 'محل تعبئة عطور',
    description: '',
    capital: 120000,
    monthlyProfit: 24000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 136,
    title: 'محل تغليف هدايا',
    description: '',
    capital: 110000,
    monthlyProfit: 22000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 137,
    title: 'محل تنظيف سجاد',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 138,
    title: 'محل تنظيف ملابس',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 139,
    title: 'محل حلاقة',
    description: '',
    capital: 120000,
    monthlyProfit: 24000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 140,
    title: 'محل خياطة',
    description: '',
    capital: 130000,
    monthlyProfit: 26000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 141,
    title: 'محل ديكورات',
    description: '',
    capital: 250000,
    monthlyProfit: 50000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 142,
    title: 'محل زينة سيارات',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 143,
    title: 'محل عطارة',
    description: '',
    capital: 140000,
    monthlyProfit: 28000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 144,
    title: 'محل قهوة',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 145,
    title: 'محل كوافير نسائي',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 146,
    title: 'محل مأكولات بحرية',
    description: '',
    capital: 300000,
    monthlyProfit: 60000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 147,
    title: 'محل مأكولات شعبية',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 148,
    title: 'محل مأكولات عربية',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 149,
    title: 'محل مخبوزات',
    description: '',
    capital: 250000,
    monthlyProfit: 50000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 150,
    title: 'محل مستلزمات الحدائق',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 151,
    title: 'محل مستلزمات الرحلات',
    description: '',
    capital: 160000,
    monthlyProfit: 32000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 152,
    title: 'محل مستلزمات زراعية',
    description: '',
    capital: 200000,
    monthlyProfit: 40000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 153,
    title: 'محل مكتبة',
    description: '',
    capital: 150000,
    monthlyProfit: 30000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 154,
    title: 'محل ملابس عسكرية',
    description: '',
    capital: 180000,
    monthlyProfit: 36000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 155,
    title: 'محل مواد غذائية',
    description: '',
    capital: 250000,
    monthlyProfit: 50000,
    studyCost: 150,
    category: 'service',
  },
  {
    id: 156,
    title: 'محل مواد كهربائية',
    description: '',
    capital: 300000,
    monthlyProfit: 60000,
    studyCost: 150,
    category: 'service',
  }
];